### ISSUE TITLE
Packagist not respecting tagged versions

### ISSUE THREAD

**Issue by JamesFreeman** [TappNetwork/laravel-aws-secrets-manager#21]
For some reason when doing a composer require it links to dev-master instead of v0.8.

Also, none of the versions are picked up on packagist.

https://packagist.org/packages/tapp/laravel-aws-secrets-manager

<img width="346" alt="Screenshot 2021-12-06 at 08 34 31" src="https://user-images.githubusercontent.com/916500/144813521-b7b387fa-d478-434e-93e8-8d8d6c7e6004.png">

**Comment by swilla** [comment]
Looks like the version string was invalid, tagged a new version and that one is being represented. 
https://github.com/TappNetwork/laravel-aws-secrets-manager/releases/tag/v0.9
